// ─── The paperwork a delivered load still owes ────────────────────────────────
// A load is delivered when the box is off the truck. It is *billable* only once
// the documents that prove the delivery are on file and somebody in the office
// has looked at them. Between those two points it sits in PAPERWORK_PENDING,
// and this file is the one definition of what "the paperwork" means and where
// the review has got to.
//
// ── The review states ────────────────────────────────────────────────────────
//
//   AWAITING_DOCUMENTS   moved to paperwork; the driver has not uploaded yet
//   IN_REVIEW            the driver has uploaded; the office has not ruled
//   CHANGES_REQUESTED    the office sent it back with a reason
//   APPROVED             signed off — the documents are locked and the load is
//                        invoiceable
//
// A re-upload puts a CHANGES_REQUESTED load back into IN_REVIEW, so the loop
// runs as many times as it needs to. APPROVED is the only one-way door.
//
// ── Why the required list is short ───────────────────────────────────────────
// Only the two documents that every load genuinely has. A Lumper Receipt or a
// Scale Ticket exists on some loads and not others, so requiring them would
// leave loads permanently un-approvable and teach everybody to ignore the
// missing-documents warning — which is the warning that has to still mean
// something on the day a Bill of Lading really is missing.
// ─────────────────────────────────────────────────────────────────────────────

const PAPERWORK_STATES = [
  "AWAITING_DOCUMENTS",
  "IN_REVIEW",
  "CHANGES_REQUESTED",
  "APPROVED",
];

const POD_DOCUMENT_TYPE = "Proof of Delivery";

// What must be on the load before the office can approve it.
const REQUIRED_PAPERWORK_DOCUMENT_TYPES = [POD_DOCUMENT_TYPE, "Bill Of Lading"];

// What the driver can actually put there. Mirrors `uploadableDocumentTypes` in
// mobile/App.js — the phone decides what to offer, this decides what counts as
// the driver having answered. The POD is not in it: it is generated by the
// server when the delivery is signed for, not uploaded by anybody.
const DRIVER_UPLOADABLE_DOCUMENT_TYPES = [
  "Bill Of Lading",
  "Scale Ticket",
  "Lumper Receipt",
  "Carrier Invoice",
  "Misc.",
];

/** The document type this load actually stores, given what somebody sent. */
const normalizeDocumentType = (documentType) =>
  documentType === "Invoice" ? "Carrier Invoice" : documentType;

const typesOn = (load) =>
  new Set((load?.documents || []).map((doc) => normalizeDocumentType(doc.documentType)));

/** Required documents that are not on the load yet, in the order they are read. */
const missingRequiredDocuments = (load) => {
  const present = typesOn(load);
  return REQUIRED_PAPERWORK_DOCUMENT_TYPES.filter((type) => !present.has(type));
};

/**
 * Has the driver put anything there at all?
 *
 * The POD does not count. It is generated on delivery, so every delivered load
 * has one — treating it as an answer would mean the office could never tell a
 * driver who uploaded nothing from a driver who uploaded everything.
 */
const hasDriverSubmittedPaperwork = (load) => {
  const present = typesOn(load);
  return DRIVER_UPLOADABLE_DOCUMENT_TYPES.some((type) => present.has(type));
};

/**
 * Are this load's documents settled?
 *
 * Approval is what locks them. After it, the file the office signed off is the
 * file that stays on the load — a driver replacing a Bill of Lading the week
 * after it was approved and invoiced against is exactly the thing this stops.
 */
const isPaperworkLocked = (load) => load?.paperwork?.state === "APPROVED";

module.exports = {
  PAPERWORK_STATES,
  POD_DOCUMENT_TYPE,
  REQUIRED_PAPERWORK_DOCUMENT_TYPES,
  DRIVER_UPLOADABLE_DOCUMENT_TYPES,
  normalizeDocumentType,
  missingRequiredDocuments,
  hasDriverSubmittedPaperwork,
  isPaperworkLocked,
};
