import { useRef, useState } from "react";
import { toast } from "react-toastify";
import api from "../api";
import UploadFileIcon from "@mui/icons-material/UploadFile";
import VisibilityIcon from "@mui/icons-material/Visibility";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import ErrorOutlineIcon from "@mui/icons-material/ErrorOutline";
import BlockIcon from "@mui/icons-material/Block";

const BASE_DOCUMENT_TYPES = [
  "Bare Chassis In-Gate/Out-Gate",
  "Bill Of Lading",
  "Out-Gate Interchange",
  "In-Gate Interchange",
  "Scale Ticket",
  "Lumper Receipt",
  "Misc.",
  "Carrier Invoice",
];

const POD_DOCUMENT_TYPE = "Proof of Delivery";

const getAvailableDocumentTypes = (transportStatus) =>
  [...BASE_DOCUMENT_TYPES, POD_DOCUMENT_TYPE];

const ViewLink = ({ filePath }) => {
  if (!filePath) return null;
  
  // Smartly sanitize absolute or legacy Windows paths 
  // ensuring the path always safely begins with "uploads/" and uses forward slashes
  const cleanPath = filePath.includes("uploads") 
    ? filePath.substring(filePath.indexOf("uploads")).replace(/\\/g, "/")
    : filePath;

  return (
    <a 
      href={`${import.meta.env.VITE_API_BASE_URL}/${cleanPath}`}
      target="_blank"
      rel="noreferrer"
      className="inline-flex items-center gap-1 text-xs font-semibold text-indigo-600 px-2.5 py-1 border border-indigo-100 rounded-md bg-indigo-50 hover:bg-indigo-100 transition-colors"
    >
      <VisibilityIcon style={{ fontSize: 13 }} /> View
    </a>
  );
};

const StatusChip = ({ isUploaded }) =>
  isUploaded ? (
    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-bold bg-green-100 text-green-700 border border-green-200 shrink-0">
      <CheckCircleOutlineIcon style={{ fontSize: 11 }} /> Uploaded
    </span>
  ) : (
    <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-bold bg-red-100 text-red-600 border border-red-300 shrink-0">
      <ErrorOutlineIcon style={{ fontSize: 11 }} /> Missing
    </span>
  );

const UploadButton = ({ type, isDisabled, isUploading, isUploaded, transportStatus, inputRef, onChange }) => (
  <>
    <input
      type="file"
      ref={inputRef}
      className="hidden"
      accept="*/*"
      disabled={isDisabled}
      onChange={onChange}
    />
    <button
      type="button"
      disabled={isDisabled}
      onClick={() => { if (!isDisabled) inputRef.current?.click(); }}
      className={`inline-flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1.5 rounded-md border transition-colors whitespace-nowrap ${
        isDisabled
          ? "text-gray-400 bg-gray-50 border-gray-200 cursor-not-allowed"
          : "text-gray-700 bg-white border-gray-200 hover:border-indigo-500 hover:text-indigo-600 cursor-pointer"
      }`}
    >
      {isDisabled ? <BlockIcon style={{ fontSize: 14 }} /> : <UploadFileIcon style={{ fontSize: 14 }} />}
      {isUploading
        ? "Uploading…"
        : transportStatus !== "DELIVERED"
        ? "Upload Disabled"
        : isUploaded
        ? "Replace"
        : "Choose File"}
    </button>
  </>
);

const AutoGeneratedBadge = ({ label = "Auto-generated" }) => (
  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-200 whitespace-nowrap">
    {label}
  </span>
);

const DeleteButton = ({ docId, isDeleting, onDelete }) => {
  if (!docId) return null;
  return (
    <button
      type="button"
      onClick={() => onDelete(docId)}
      disabled={isDeleting}
      className={`inline-flex items-center gap-1 text-xs font-semibold px-2.5 py-1.5 rounded-md border transition-colors ${
        isDeleting
          ? "text-gray-400 bg-gray-50 border-gray-200 cursor-not-allowed"
          : "text-red-600 bg-white border-red-300 hover:bg-red-50 cursor-pointer"
      }`}
    >
      <DeleteOutlineIcon style={{ fontSize: 14 }} />
      {isDeleting ? "…" : "Delete"}
    </button>
  );
};

const DocumentUpload = ({ loadId, transportStatus, documents = [], refresh }) => {
  const [uploadingType, setUploadingType] = useState(null);
  const [deletingId, setDeletingId] = useState(null);
  const desktopRefs = useRef({});
  const mobileRefs = useRef({});

  const documentTypes = getAvailableDocumentTypes(transportStatus);

  const getDocByType = (type) =>
    documents.find(
      (doc) =>
        (doc.documentType === "Invoice" ? "Carrier Invoice" : doc.documentType) === type,
    );

  const handleUpload = async (type, file) => {
    if (!file) return toast.error("Please select a file first");
    const formData = new FormData();
    formData.append("file", file);
    formData.append("documentType", type);
    try {
      setUploadingType(type);
      await api.post(`/loads/${loadId}/documents`, formData);
      toast.success(`${type} uploaded successfully`);
      if (desktopRefs.current[type]) desktopRefs.current[type].value = "";
      if (mobileRefs.current[type]) mobileRefs.current[type].value = "";
      refresh();
    } catch (err) {
      toast.error(err?.response?.data?.message || "Upload failed");
    } finally {
      setUploadingType(null);
    }
  };

  const handleDelete = async (docId) => {
    try {
      setDeletingId(docId);
      await api.delete(`/loads/${loadId}/documents/${docId}`);
      toast.success("Document deleted");
      refresh();
    } catch {
      toast.error("Delete failed");
    } finally {
      setDeletingId(null);
    }
  };

  const uploaded = documentTypes.filter((t) => getDocByType(t)).length;
  const total = documentTypes.length;
  const pct = Math.round((uploaded / total) * 100);

  return (
    <div className="font-sans">
      {/* Progress bar */}
      <div className="flex items-center gap-4 mb-4 px-4 py-3 bg-gray-50 rounded-xl border border-gray-100">
        <div className="flex-1">
          <div className="flex justify-between mb-1.5">
            <span className="text-xs font-bold text-gray-500 uppercase tracking-wide">
              Document Completion
            </span>
            <span className={`text-xs font-bold ${pct === 100 ? "text-green-700" : "text-indigo-600"}`}>
              {uploaded} / {total} uploaded
            </span>
          </div>
          <div className="h-1.5 bg-gray-200 rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ${pct === 100 ? "bg-green-500" : "bg-indigo-500"}`}
              style={{ width: `${pct}%` }}
            />
          </div>
        </div>
        <div
          className={`px-3 py-1 rounded-full text-xs font-bold whitespace-nowrap border ${
            pct === 100
              ? "bg-green-100 text-green-700 border-green-200"
              : "bg-violet-100 text-violet-700 border-violet-300"
          }`}
        >
          {pct}% complete
        </div>
      </div>

      {/* Desktop Table */}
      <div className="hidden md:block border border-gray-100 rounded-xl overflow-hidden">
        {/* Header */}
        <div className="grid grid-cols-[2fr_110px_1.5fr_80px_150px_90px] bg-gray-50 border-b border-gray-200 px-4 py-2">
          {["Document", "Status", "File", "View", "Upload", "Delete"].map((h) => (
            <div key={h} className="text-xs font-bold text-gray-400 uppercase tracking-widest">
              {h}
            </div>
          ))}
        </div>

        {/* Rows */}
        {documentTypes.map((type, idx) => {
          const doc = getDocByType(type);
          const isUploaded = !!doc;
          const isUploading = uploadingType === type;
          const isDeleting = deletingId === doc?._id;
          const isPodDoc = type === POD_DOCUMENT_TYPE;
          const isDelivered = transportStatus === "DELIVERED";
          const isDisabled = isUploading || (isPodDoc && !isDelivered);

          return (
            <div
              key={type}
              className={`grid grid-cols-[2fr_110px_1.5fr_80px_150px_90px] px-4 py-2.5 items-center transition-colors hover:bg-slate-50 ${
                idx < documentTypes.length - 1 ? "border-b border-gray-50" : ""
              } ${isUploaded ? "bg-teal-50/30" : "bg-white"}`}
            >
              <div className="text-sm font-medium text-gray-800 pr-2">{type}</div>

              <div>
                <StatusChip isUploaded={isUploaded} />
              </div>

              <div className={`text-xs pr-2 truncate ${doc?.fileName ? "text-gray-700" : "text-gray-300 italic"}`}>
                {doc?.fileName || "No file"}
              </div>

              <div>
                <ViewLink filePath={doc?.filePath} />
              </div>

              <div>
                {isPodDoc ? (
                  isDelivered ? (
                    <AutoGeneratedBadge />
                  ) : (
                    <AutoGeneratedBadge label="Auto-generated on delivery" />
                  )
                ) : (
                  <>
                    {/* Use raw input+button inline to keep ref working correctly */}
                    <input
                      type="file"
                      ref={(el) => { desktopRefs.current[type] = el; }}
                      className="hidden"
                      accept="*/*"
                      disabled={isDisabled}
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (file) handleUpload(type, file);
                      }}
                    />
                    <button
                      type="button"
                      disabled={isDisabled}
                      onClick={() => { if (!isDisabled) desktopRefs.current[type]?.click(); }}
                      className={`inline-flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1.5 rounded-md border transition-colors whitespace-nowrap ${
                        isDisabled
                          ? "text-gray-400 bg-gray-50 border-gray-200 cursor-not-allowed"
                          : "text-gray-700 bg-white border-gray-200 hover:border-indigo-500 hover:text-indigo-600 cursor-pointer"
                      }`}
                    >
                      {isDisabled ? <BlockIcon style={{ fontSize: 14 }} /> : <UploadFileIcon style={{ fontSize: 14 }} />}
                      {isUploading ? "Uploading…" : isUploaded ? "Replace" : "Choose File"}
                    </button>
                  </>
                )}
              </div>

              <div>
                {isPodDoc ? null : <DeleteButton docId={doc?._id} isDeleting={isDeleting} onDelete={handleDelete} />}
              </div>
            </div>
          );
        })}
      </div>

      {/* Mobile Cards */}
      <div className="flex flex-col gap-3 md:hidden">
        {documentTypes.map((type) => {
          const doc = getDocByType(type);
          const isUploaded = !!doc;
          const isUploading = uploadingType === type;
          const isDeleting = deletingId === doc?._id;
          const isPodDoc = type === POD_DOCUMENT_TYPE;
          const isDelivered = transportStatus === "DELIVERED";
          const isDisabled = isUploading || (isPodDoc && !isDelivered);

          return (
            <div
              key={type}
              className={`rounded-xl border px-4 py-3 flex flex-col gap-2 ${
                isUploaded ? "bg-teal-50/30 border-teal-100" : "bg-white border-gray-100"
              }`}
            >
              {/* Name + status */}
              <div className="flex items-start justify-between gap-2">
                <span className="text-sm font-semibold text-gray-800 leading-snug">{type}</span>
                <StatusChip isUploaded={isUploaded} />
              </div>

              {/* File name */}
              {doc?.fileName && (
                <div className="text-xs text-gray-500 truncate">📄 {doc.fileName}</div>
              )}

              {/* Actions */}
              <div className="flex items-center gap-2 flex-wrap pt-1">
                <ViewLink filePath={doc?.filePath} />
                {isPodDoc ? (
                  isDelivered ? (
                    <AutoGeneratedBadge />
                  ) : (
                    <AutoGeneratedBadge label="Auto-generated on delivery" />
                  )
                ) : (
                  <>
                    <input
                      type="file"
                      ref={(el) => { mobileRefs.current[type] = el; }}
                      className="hidden"
                      accept="*/*"
                      disabled={isDisabled}
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (file) handleUpload(type, file);
                      }}
                    />
                    <button
                      type="button"
                      disabled={isDisabled}
                      onClick={() => { if (!isDisabled) mobileRefs.current[type]?.click(); }}
                      className={`inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-md border transition-colors ${
                        isDisabled
                          ? "text-gray-400 bg-gray-50 border-gray-200 cursor-not-allowed"
                          : "text-gray-700 bg-white border-gray-200 hover:border-indigo-500 hover:text-indigo-600 cursor-pointer"
                      }`}
                    >
                      {isDisabled ? <BlockIcon style={{ fontSize: 14 }} /> : <UploadFileIcon style={{ fontSize: 14 }} />}
                      {isUploading ? "Uploading…" : isUploaded ? "Replace" : "Upload"}
                    </button>

                    <div className="ml-auto">
                      <DeleteButton docId={doc?._id} isDeleting={isDeleting} onDelete={handleDelete} />
                    </div>
                  </>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default DocumentUpload;